/**
 * Demo-mode universe: a fixed set of well-known symbols with static profile
 * facts (name, sector, industry) and per-symbol parameters that drive the
 * deterministic synthetic price generator. Static facts are real-world
 * descriptors; every PRICE derived from these params is synthetic and labeled.
 */

export type UniverseEntry = {
  symbol: string;
  name: string;
  sector: string;
  industry: string;
  exchange: string;
  etf?: boolean;
  /** synthetic-series params */
  basePriceCents: number; // anchor price at series start
  drift: number; // annualized drift, e.g. 0.10
  vol: number; // annualized volatility, e.g. 0.30
  divYield: number | null;
};

export const UNIVERSE: UniverseEntry[] = [
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    sector: "Index",
    industry: "Broad Market ETF",
    exchange: "NYSEARCA",
    etf: true,
    basePriceCents: 20000,
    drift: 0.09,
    vol: 0.15,
    divYield: 0.013,
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    sector: "Index",
    industry: "Nasdaq-100 ETF",
    exchange: "NASDAQ",
    etf: true,
    basePriceCents: 10000,
    drift: 0.13,
    vol: 0.2,
    divYield: 0.006,
  },
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    industry: "Consumer Electronics",
    exchange: "NASDAQ",
    basePriceCents: 2700,
    drift: 0.18,
    vol: 0.28,
    divYield: 0.005,
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    sector: "Technology",
    industry: "Software — Infrastructure",
    exchange: "NASDAQ",
    basePriceCents: 4000,
    drift: 0.17,
    vol: 0.26,
    divYield: 0.008,
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    exchange: "NASDAQ",
    basePriceCents: 2600,
    drift: 0.14,
    vol: 0.29,
    divYield: 0.004,
  },
  {
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    exchange: "NASDAQ",
    basePriceCents: 1550,
    drift: 0.15,
    vol: 0.32,
    divYield: null,
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    basePriceCents: 500,
    drift: 0.35,
    vol: 0.48,
    divYield: 0.001,
  },
  {
    symbol: "META",
    name: "Meta Platforms, Inc.",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    exchange: "NASDAQ",
    basePriceCents: 7800,
    drift: 0.16,
    vol: 0.38,
    divYield: 0.004,
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    exchange: "NASDAQ",
    basePriceCents: 1500,
    drift: 0.2,
    vol: 0.55,
    divYield: null,
  },
  {
    symbol: "AVGO",
    name: "Broadcom Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    basePriceCents: 1100,
    drift: 0.25,
    vol: 0.32,
    divYield: 0.014,
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices, Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    basePriceCents: 250,
    drift: 0.22,
    vol: 0.5,
    divYield: null,
  },
  {
    symbol: "INTC",
    name: "Intel Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    basePriceCents: 3600,
    drift: 0.0,
    vol: 0.38,
    divYield: 0.015,
  },
  {
    symbol: "CRM",
    name: "Salesforce, Inc.",
    sector: "Technology",
    industry: "Software — Application",
    exchange: "NYSE",
    basePriceCents: 5800,
    drift: 0.12,
    vol: 0.34,
    divYield: 0.006,
  },
  {
    symbol: "ORCL",
    name: "Oracle Corporation",
    sector: "Technology",
    industry: "Software — Infrastructure",
    exchange: "NYSE",
    basePriceCents: 4400,
    drift: 0.16,
    vol: 0.3,
    divYield: 0.011,
  },
  {
    symbol: "ADBE",
    name: "Adobe Inc.",
    sector: "Technology",
    industry: "Software — Application",
    exchange: "NASDAQ",
    basePriceCents: 7300,
    drift: 0.11,
    vol: 0.33,
    divYield: null,
  },
  {
    symbol: "NFLX",
    name: "Netflix, Inc.",
    sector: "Communication Services",
    industry: "Entertainment",
    exchange: "NASDAQ",
    basePriceCents: 4900,
    drift: 0.15,
    vol: 0.4,
    divYield: null,
  },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    sector: "Communication Services",
    industry: "Entertainment",
    exchange: "NYSE",
    basePriceCents: 9400,
    drift: 0.03,
    vol: 0.3,
    divYield: 0.009,
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    sector: "Financial Services",
    industry: "Credit Services",
    exchange: "NYSE",
    basePriceCents: 6600,
    drift: 0.13,
    vol: 0.22,
    divYield: 0.008,
  },
  {
    symbol: "MA",
    name: "Mastercard Incorporated",
    sector: "Financial Services",
    industry: "Credit Services",
    exchange: "NYSE",
    basePriceCents: 8100,
    drift: 0.14,
    vol: 0.23,
    divYield: 0.006,
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    sector: "Financial Services",
    industry: "Banks — Diversified",
    exchange: "NYSE",
    basePriceCents: 5600,
    drift: 0.12,
    vol: 0.25,
    divYield: 0.022,
  },
  {
    symbol: "BAC",
    name: "Bank of America Corporation",
    sector: "Financial Services",
    industry: "Banks — Diversified",
    exchange: "NYSE",
    basePriceCents: 1600,
    drift: 0.08,
    vol: 0.28,
    divYield: 0.025,
  },
  {
    symbol: "GS",
    name: "The Goldman Sachs Group, Inc.",
    sector: "Financial Services",
    industry: "Capital Markets",
    exchange: "NYSE",
    basePriceCents: 18000,
    drift: 0.11,
    vol: 0.28,
    divYield: 0.02,
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    exchange: "NYSE",
    basePriceCents: 7700,
    drift: 0.06,
    vol: 0.28,
    divYield: 0.033,
  },
  {
    symbol: "CVX",
    name: "Chevron Corporation",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    exchange: "NYSE",
    basePriceCents: 10400,
    drift: 0.05,
    vol: 0.26,
    divYield: 0.04,
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group Incorporated",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    exchange: "NYSE",
    basePriceCents: 24000,
    drift: 0.12,
    vol: 0.24,
    divYield: 0.014,
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    exchange: "NYSE",
    basePriceCents: 10000,
    drift: 0.06,
    vol: 0.17,
    divYield: 0.03,
  },
  {
    symbol: "PFE",
    name: "Pfizer Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    exchange: "NYSE",
    basePriceCents: 3200,
    drift: 0.0,
    vol: 0.26,
    divYield: 0.058,
  },
  {
    symbol: "LLY",
    name: "Eli Lilly and Company",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    exchange: "NYSE",
    basePriceCents: 8200,
    drift: 0.3,
    vol: 0.32,
    divYield: 0.007,
  },
  {
    symbol: "MRK",
    name: "Merck & Co., Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    exchange: "NYSE",
    basePriceCents: 7500,
    drift: 0.06,
    vol: 0.22,
    divYield: 0.03,
  },
  {
    symbol: "ABBV",
    name: "AbbVie Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    exchange: "NYSE",
    basePriceCents: 8800,
    drift: 0.1,
    vol: 0.24,
    divYield: 0.035,
  },
  {
    symbol: "KO",
    name: "The Coca-Cola Company",
    sector: "Consumer Defensive",
    industry: "Beverages — Non-Alcoholic",
    exchange: "NYSE",
    basePriceCents: 4200,
    drift: 0.05,
    vol: 0.16,
    divYield: 0.03,
  },
  {
    symbol: "PEP",
    name: "PepsiCo, Inc.",
    sector: "Consumer Defensive",
    industry: "Beverages — Non-Alcoholic",
    exchange: "NASDAQ",
    basePriceCents: 9600,
    drift: 0.05,
    vol: 0.17,
    divYield: 0.031,
  },
  {
    symbol: "PG",
    name: "The Procter & Gamble Company",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    exchange: "NYSE",
    basePriceCents: 9100,
    drift: 0.06,
    vol: 0.16,
    divYield: 0.024,
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    exchange: "NYSE",
    basePriceCents: 2900,
    drift: 0.11,
    vol: 0.19,
    divYield: 0.011,
  },
  {
    symbol: "COST",
    name: "Costco Wholesale Corporation",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    exchange: "NASDAQ",
    basePriceCents: 14200,
    drift: 0.15,
    vol: 0.22,
    divYield: 0.005,
  },
  {
    symbol: "HD",
    name: "The Home Depot, Inc.",
    sector: "Consumer Cyclical",
    industry: "Home Improvement Retail",
    exchange: "NYSE",
    basePriceCents: 10400,
    drift: 0.1,
    vol: 0.23,
    divYield: 0.024,
  },
  {
    symbol: "MCD",
    name: "McDonald's Corporation",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    exchange: "NYSE",
    basePriceCents: 9400,
    drift: 0.09,
    vol: 0.18,
    divYield: 0.022,
  },
  {
    symbol: "NKE",
    name: "NIKE, Inc.",
    sector: "Consumer Cyclical",
    industry: "Footwear & Accessories",
    exchange: "NYSE",
    basePriceCents: 4700,
    drift: 0.02,
    vol: 0.3,
    divYield: 0.016,
  },
  {
    symbol: "SBUX",
    name: "Starbucks Corporation",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    exchange: "NASDAQ",
    basePriceCents: 4000,
    drift: 0.05,
    vol: 0.28,
    divYield: 0.025,
  },
  {
    symbol: "BA",
    name: "The Boeing Company",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    exchange: "NYSE",
    basePriceCents: 13000,
    drift: -0.02,
    vol: 0.4,
    divYield: null,
  },
  {
    symbol: "CAT",
    name: "Caterpillar Inc.",
    sector: "Industrials",
    industry: "Farm & Heavy Construction Machinery",
    exchange: "NYSE",
    basePriceCents: 9100,
    drift: 0.13,
    vol: 0.27,
    divYield: 0.016,
  },
  {
    symbol: "GE",
    name: "GE Aerospace",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    exchange: "NYSE",
    basePriceCents: 660,
    drift: 0.14,
    vol: 0.34,
    divYield: 0.005,
  },
  {
    symbol: "HON",
    name: "Honeywell International Inc.",
    sector: "Industrials",
    industry: "Conglomerates",
    exchange: "NASDAQ",
    basePriceCents: 14500,
    drift: 0.06,
    vol: 0.2,
    divYield: 0.021,
  },
  {
    symbol: "UPS",
    name: "United Parcel Service, Inc.",
    sector: "Industrials",
    industry: "Integrated Freight & Logistics",
    exchange: "NYSE",
    basePriceCents: 9700,
    drift: 0.02,
    vol: 0.25,
    divYield: 0.045,
  },
  {
    symbol: "T",
    name: "AT&T Inc.",
    sector: "Communication Services",
    industry: "Telecom Services",
    exchange: "NYSE",
    basePriceCents: 3400,
    drift: 0.0,
    vol: 0.22,
    divYield: 0.06,
  },
  {
    symbol: "VZ",
    name: "Verizon Communications Inc.",
    sector: "Communication Services",
    industry: "Telecom Services",
    exchange: "NYSE",
    basePriceCents: 4600,
    drift: -0.01,
    vol: 0.2,
    divYield: 0.065,
  },
];

export const UNIVERSE_BY_SYMBOL = new Map(UNIVERSE.map((u) => [u.symbol, u]));

export function isKnownSymbol(symbol: string): boolean {
  return UNIVERSE_BY_SYMBOL.has(symbol.toUpperCase());
}
